/** Declaration file generated by dts-gen */

export function get(options: any, cb: any): any;

export function request(options: any, cb: any): any;

export namespace get {
    const prototype: {
    };

}

export namespace request {
    const prototype: {
    };

}

