/** Declaration file generated by dts-gen */

export function Agent(options: any): void;

export function get(options: any, cb: any): any;

export function request(options: any, cb: any): any;

export namespace Agent {
    namespace prototype {
        function addListener(type: any, listener: any): any;

        function addRequest(req: any, options: any, port: any, localAddress: any): void;

        function createConnection(args: any): any;

        function createSocket(req: any, options: any, cb: any): any;

        function destroy(): void;

        function emit(type: any, args: any): any;

        function eventNames(): any;

        function getMaxListeners(): any;

        function getName(options: any): any;

        function keepSocketAlive(socket: any): any;

        function listenerCount(type: any): any;

        function listeners(type: any): any;

        function off(type: any, listener: any): any;

        function on(type: any, listener: any): any;

        function once(type: any, listener: any): any;

        function prependListener(type: any, listener: any): any;

        function prependOnceListener(type: any, listener: any): any;

        function rawListeners(type: any): any;

        function removeAllListeners(type: any, ...args: any[]): any;

        function removeListener(type: any, listener: any): any;

        function removeSocket(s: any, options: any): void;

        function reuseSocket(socket: any, req: any): void;

        function setMaxListeners(n: any): any;

        namespace addListener {
            const prototype: {
            };

        }

        namespace addRequest {
            const prototype: {
            };

        }

        namespace createConnection {
            const prototype: {
            };

        }

        namespace createSocket {
            const prototype: {
            };

        }

        namespace destroy {
            const prototype: {
            };

        }

        namespace emit {
            const prototype: {
            };

        }

        namespace eventNames {
            const prototype: {
            };

        }

        namespace getMaxListeners {
            const prototype: {
            };

        }

        namespace getName {
            const prototype: {
            };

        }

        namespace keepSocketAlive {
            const prototype: {
            };

        }

        namespace listenerCount {
            const prototype: {
            };

        }

        namespace listeners {
            const prototype: {
            };

        }

        namespace off {
            const prototype: {
            };

        }

        namespace on {
            const prototype: {
            };

        }

        namespace once {
            const prototype: {
            };

        }

        namespace prependListener {
            const prototype: {
            };

        }

        namespace prependOnceListener {
            const prototype: {
            };

        }

        namespace rawListeners {
            const prototype: {
            };

        }

        namespace removeAllListeners {
            const prototype: {
            };

        }

        namespace removeListener {
            const prototype: {
            };

        }

        namespace removeSocket {
            const prototype: {
            };

        }

        namespace reuseSocket {
            const prototype: {
            };

        }

        namespace setMaxListeners {
            const prototype: {
            };

        }

    }

}

export namespace get {
    const prototype: {
    };

}

export namespace request {
    const prototype: {
    };

}

